version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: staff_pulse_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: test_task
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: staff_pulse_go_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: "1234"
      DB_NAME: test_task
      DB_SSLMODE: disable
      PORT: 8080
    ports:
      - "8080:8080"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: staff_pulse_react_client
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata:
